In [2]:
import torch
input_ids = torch.tensor([2, 3, 5, 1])
print(input_ids)


tensor([2, 3, 5, 1])


In [3]:
vocal_size=6
out_dim=3

In [4]:
embedding_layer=torch.nn.Embedding(vocal_size,out_dim)

In [5]:
print(embedding_layer.weight)

Parameter containing:
tensor([[-1.3975,  0.8970,  1.5051],
        [-0.0363, -1.7302,  0.4343],
        [-1.6310,  0.1329,  0.1931],
        [ 0.0218, -0.3869,  0.1888],
        [-0.4875, -1.1832,  0.3513],
        [ 0.2697,  1.2832, -0.1497]], requires_grad=True)


In [6]:
print(embedding_layer(torch.tensor([3])))

tensor([[ 0.0218, -0.3869,  0.1888]], grad_fn=<EmbeddingBackward0>)


In [7]:
print(embedding_layer(input_ids))

tensor([[-1.6310,  0.1329,  0.1931],
        [ 0.0218, -0.3869,  0.1888],
        [ 0.2697,  1.2832, -0.1497],
        [-0.0363, -1.7302,  0.4343]], grad_fn=<EmbeddingBackward0>)
